<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ImDiskGui</AssemblyName>
    <RootNamespace>ImDiskGui</RootNamespace>
    <LangVersion>8.0</LangVersion>
    <Prefer32Bit>false</Prefer32Bit>
    <ApplicationIcon>imdisk.ico</ApplicationIcon>
    <Version>1.0.1.0</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\about-avatar.png" />
    <Resource Include="Assets\about-avatar.png" />
    <Resource Include="imdisk.ico" />
    <Resource Include="Assets\imdisk-avatar-tray-16.png" />
  </ItemGroup>

</Project>
